server:
  port: '8070'

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/springpjt?useSSL=false&allowPublicKeyRetrieval=true&characterEncoding=UTF-8&serverTimezone=UTC
    password: whdrjffbs12!

  jpa:
    open-in-view: 'true'
    properties:
      hibernate:
        format_sql: 'true'
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: 'true'

  security:
    user:
      name: test
      password: '1234'


file:
  path: F:/springpjt/upload2/data/
